function [fitresult, gof] = createFit2gaus(aa2, aa3)
%CREATEFIT(AA2,AA3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : aa2
%      Y Output: aa3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Feb-2017 15:26:25


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( aa2, aa3 );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1e-16;
opts.Display = 'Off';
%opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
%opts.StartPoint = [2943 7.5075075075074e-09 1.92822349089849e-08 2265.47653083427 -2.85285285285286e-08 2.75281779105034e-08];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
hold all
h = plot( fitresult, xData, yData );
legend( h, 'aa3 vs. aa2', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel aa2
ylabel aa3
grid on


